import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

const origin = 'http://127.0.0.1:8078';
const storage = process.env.APP_TEST_STORAGE || join(process.cwd(), '.runtime', 'test-http');
let cookie = '';
const request = async (path, options = {}) => {
  const response = await fetch(origin + path, {...options, headers:{...options.headers, Cookie:cookie}});
  const session = response.headers.getSetCookie().find(value => value.startsWith('alin_booking='));
  if (session) cookie = session.split(';')[0];
  return response;
};
const post = (path, data) => request(path, {method:'POST',body:new URLSearchParams(data)});
assert.equal((await request('/')).status, 200);
const token = await (await request('/api/token.php')).json();
assert.ok(token.csrf && token.request_id);
assert.equal((await post('/api/booking.php', {})).status, 403);
const availabilityResponse = await request('/api/availability.php?service=terapeutic');
assert.equal(availabilityResponse.status, 200);
const availability = await availabilityResponse.json();
assert.ok(availability.days.length && availability.days[0].slots.length);
const future = availability.days[0].date;
const availableTime = availability.days[0].slots[0];
const payload = {csrf:token.csrf,request_id:token.request_id,service:'terapeutic',plan:'single',sessions:'1',date:future,time:availableTime,name:'Client Test Local',email:'client-test@example.com',phone:'0773000000',zone:'sector-1',privacy:'1',website:'',price:'1'};
await new Promise(resolve => setTimeout(resolve, 2100));
assert.equal((await post('/api/booking.php', {...payload,email:''})).status, 422);
assert.equal((await post('/api/booking.php', {...payload,date:'2020-01-01'})).status, 422);
const result = await post('/api/booking.php', payload);
assert.equal(result.status, 200, await result.clone().text());
assert.equal((await result.json()).ok, true);
const recordPath = join(storage, `${token.request_id}.json`);
let record = JSON.parse(await readFile(recordPath, 'utf8'));
assert.equal(record.status, 'pending');
assert.equal(record.price, 200); assert.equal(record.total, 230); assert.equal(record.sessions, 1); assert.equal(record.plan, 'single');
assert.equal(record.amount, 230); assert.equal(record.payment_status, 'unpaid');
assert.equal(record.source, 'site');
assert.ok(record.delivery.owner && record.delivery.receipt);
const originalTimes = {...record.delivery};
assert.equal((await post('/api/booking.php', payload)).status, 200);
record = JSON.parse(await readFile(recordPath, 'utf8'));
assert.deepEqual(record.delivery, originalTimes);
assert.equal((await post('/api/booking.php', {...payload,email:'different@example.com'})).status, 409);
let secondCookie = '';
const secondRequest = async (path, options = {}) => { const response = await fetch(origin + path, {...options, headers:{...options.headers, Cookie:secondCookie}}); const session = response.headers.getSetCookie().find(value => value.startsWith('alin_booking=')); if (session) secondCookie = session.split(';')[0]; return response; };
const secondToken = await (await secondRequest('/api/token.php')).json();
await new Promise(resolve => setTimeout(resolve, 2100));
const conflict = await secondRequest('/api/booking.php', {method:'POST',body:new URLSearchParams({...payload,csrf:secondToken.csrf,request_id:secondToken.request_id,email:'second-client@example.com'})});
assert.equal(conflict.status, 409);
assert.equal((await request(`/confirmare.php?id=${record.id}&token=invalid`)).status, 404);
const manage = `/confirmare.php?id=${record.id}&token=${record.manage_token}`;
const page = await (await request(manage)).text();
assert.match(page, /În așteptarea confirmării/);
assert.equal(JSON.parse(await readFile(recordPath, 'utf8')).status, 'pending');
assert.equal((await post(manage, {csrf:'invalid'})).status, 403);
const csrf = /name="csrf" value="([^"]+)"/.exec(page)[1];
assert.equal((await post(manage, {csrf})).status, 200);
record = JSON.parse(await readFile(recordPath, 'utf8'));
assert.equal(record.status, 'confirmed'); assert.ok(record.delivery.confirmed);
const confirmedTime = record.delivery.confirmed;
const repeatedConfirmation = await post(manage, {csrf});
assert.equal(repeatedConfirmation.status, 200);
assert.match(await repeatedConfirmation.text(), /deja confirmată/);
assert.equal(JSON.parse(await readFile(recordPath, 'utf8')).delivery.confirmed, confirmedTime);
const mails = (await readdir(storage)).filter(name => name.startsWith(record.id) && name.endsWith('.eml'));
assert.equal(mails.length, 3);
const ownerMail = await readFile(join(storage, `${record.id}-owner.eml`), 'utf8');
const receiptMail = await readFile(join(storage, `${record.id}-receipt.eml`), 'utf8');
assert.match(ownerMail, /To: Alin Bughius <bughius_alin@yahoo.com>/);
assert.match(receiptMail, /To: Client Test Local <client-test@example.com>/);
assert.match(ownerMail, /From: Alin Bughius <contact@alinbughius.ro>/);
assert.ok(!receiptMail.includes(record.manage_token));
for (const path of ['/config/local.php','/app/catalog.php','/storage/' + record.id + '.json','/vendor/PHPMailer/README.md']) assert.equal((await request(path)).status, 404, `${path} private`);
assert.equal((await request('/admin/')).status, 200);
console.log('PASS: live availability, atomic slot protection, form validation, pricing, receipts, private approval, confirmation and admin entry. All email captured locally.');
